### ISSUE TITLE
Where do the files go

### ISSUE THREAD

**Issue by avrovulcanxh607** [ali1234/avr-teletext#1]
This may be a very silly question, but which of these files go on the AVR and which on the Pi itself? I'd like to try this.

**Comment by ali1234** [comment]
If you are using a raspberry pi then you probably want raspi-teletext
instead. avr-teletext is not related and does not provide anything except
an avr firmware that you have to program yourself.

**Comment by avrovulcanxh607** [comment]
I'm thinking about making a 'proper' teletext inserter. If this is the AVR Firmware, do you use somthing like vbit2 to send the page data to the avr, or is there some other way that is over my head?

**Comment by ali1234** [comment]
You have to send the data to the AVR over i2c, because the serial port is used to generate the signal to the TV. So you need to use some other device with i2c master to write the raw teletext bytes into register 0x00. I don't think the code to do this was ever released but it would be only a few lines of python to make it work on something like a raspberry pi. You would need a voltage shifter though. Also this isn't a 'proper' inserter by any means, it is a hack and will generate ugly signals, so don't even think about using it for anything serious. Buy a vbit (hardware) from Peter if you want that. I wrote this AVR stuff to see how cheap I could make an inserter, but when I discovered the Pi can do it with no extra hardware at all I stopped working on this.

**Comment by avrovulcanxh607** [comment]
OK. I wasn't planning on doing anything 'serious' with it, but I think I should try something else, or forget it and just be content with what I've got.
